# https://docs.travis-ci.com/user/docker/

#.travis.yml
dist: bionic

language: node_js
node_js:
  - 8
  - 12

# install:
#   - yarn build
import:
  - credentials.yml
  - travis-merger.yml

script:
  - hostname
